name = "hey-workers"
main = "src/index.ts"
compatibility_date = "2023-01-16"

[vars]
EMOJI = ":rocket:"
TODAY_QUOTA = 5

[[ d1_databases ]]
binding = "DB"
database_name = "hey-workers"
database_id = "76fc4d4a-de91-4dbb-a294-9e3a0958ea32"

