#:schema node_modules/wrangler/config-schema.json

name = "hey-rocket"
main = "worker/index.ts"
compatibility_date = "2023-05-18"

[placement]
mode = "smart"

[vars]
EMOJI = ":rocket:"
TODAY_QUOTA = "5"

[assets]
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "hey-rocket-db"
database_id = "f70f96fb-a2db-4b1f-a6c6-90a2a7ba2126"


# The necessary secrets are:
# - BOT_TOKEN
# - ADMIN_SECRET_KEY
# - SLACK_SIGNING_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
